---
- name: Actualizar sistemas Ubuntu, RedHat y Rocky
  hosts: all
  become: yes

  tasks:
    - name: Actualizar la lista de paquetes
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600 # Actualiza la caché si tiene más de 1 hora
      when: ansible_facts['os_family'] == "Debian"

    - name: Actualizar todos los paquetes en RedHat/CentOS
      ansible.builtin.yum:
        name: '*'
        state: latest
      when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution'] != "Rocky"

    - name: Actualizar todos los paquetes en Rocky Linux
      ansible.builtin.dnf:
        name: '*'
        state: latest
      when: ansible_facts['distribution'] == "Rocky"
